# Generated by Django 5.0.3 on 2024-05-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('hoca', models.CharField(blank=True, max_length=250, null=True)),
                ('photo_ders', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_hoca', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('body', models.IntegerField(blank=True, null=True)),
                ('saat', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('mevcut', 'mevcut'), ('alindigi', 'alindigi'), ('yok', 'yok')], max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='msy_app.category')),
            ],
        ),
    ]
