# Generated by Django 5.0.6 on 2024-06-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msy_app', '0002_ders_toplam_saat_alter_ders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('absence_hours', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('dersler', models.ManyToManyField(to='msy_app.ders')),
            ],
        ),
    ]
