# Generated by Django 5.0.6 on 2024-06-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msy_app', '0003_ogrenci'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
